import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Define constants for enums (SQLite uses strings)
const NoteCategory = {
  CITRUS: "CITRUS",
  FLORAL: "FLORAL",
  WOODY: "WOODY",
  ORIENTAL: "ORIENTAL",
  FRESH: "FRESH",
  SPICY: "SPICY",
  FRUITY: "FRUITY",
  GREEN: "GREEN",
  AQUATIC: "AQUATIC",
  GOURMAND: "GOURMAND",
  MUSK: "MUSK",
  AMBER: "AMBER",
  LEATHER: "LEATHER",
  AROMATIC: "AROMATIC",
} as const;

const NoteLayer = {
  TOP: "TOP",
  MIDDLE: "MIDDLE",
  BASE: "BASE",
} as const;

const Concentration = {
  EAU_FRAICHE: "EAU_FRAICHE",
  EAU_DE_COLOGNE: "EAU_DE_COLOGNE",
  EAU_DE_TOILETTE: "EAU_DE_TOILETTE",
  EAU_DE_PARFUM: "EAU_DE_PARFUM",
  PARFUM: "PARFUM",
  EXTRAIT: "EXTRAIT",
} as const;

const Gender = {
  MASCULINE: "MASCULINE",
  FEMININE: "FEMININE",
  UNISEX: "UNISEX",
} as const;

async function main() {
  console.log("Starting seed...");

  // Clear existing data
  await prisma.activity.deleteMany();
  await prisma.reviewLike.deleteMany();
  await prisma.listItem.deleteMany();
  await prisma.list.deleteMany();
  await prisma.userFollow.deleteMany();
  await prisma.userFragrance.deleteMany();
  await prisma.review.deleteMany();
  await prisma.fragranceNote.deleteMany();
  await prisma.fragrance.deleteMany();
  await prisma.note.deleteMany();
  await prisma.brand.deleteMany();

  console.log("Creating notes...");

  // Create Notes
  const notesData = [
    // Citrus
    { name: "Bergamot", slug: "bergamot", category: NoteCategory.CITRUS },
    { name: "Lemon", slug: "lemon", category: NoteCategory.CITRUS },
    { name: "Orange", slug: "orange", category: NoteCategory.CITRUS },
    { name: "Grapefruit", slug: "grapefruit", category: NoteCategory.CITRUS },
    { name: "Mandarin", slug: "mandarin", category: NoteCategory.CITRUS },
    { name: "Lime", slug: "lime", category: NoteCategory.CITRUS },
    { name: "Yuzu", slug: "yuzu", category: NoteCategory.CITRUS },

    // Floral
    { name: "Rose", slug: "rose", category: NoteCategory.FLORAL },
    { name: "Jasmine", slug: "jasmine", category: NoteCategory.FLORAL },
    { name: "Iris", slug: "iris", category: NoteCategory.FLORAL },
    { name: "Violet", slug: "violet", category: NoteCategory.FLORAL },
    { name: "Lily of the Valley", slug: "lily-of-the-valley", category: NoteCategory.FLORAL },
    { name: "Tuberose", slug: "tuberose", category: NoteCategory.FLORAL },
    { name: "Peony", slug: "peony", category: NoteCategory.FLORAL },
    { name: "Magnolia", slug: "magnolia", category: NoteCategory.FLORAL },
    { name: "Orange Blossom", slug: "orange-blossom", category: NoteCategory.FLORAL },
    { name: "Ylang Ylang", slug: "ylang-ylang", category: NoteCategory.FLORAL },
    { name: "Lavender", slug: "lavender", category: NoteCategory.AROMATIC },

    // Woody
    { name: "Sandalwood", slug: "sandalwood", category: NoteCategory.WOODY },
    { name: "Cedar", slug: "cedar", category: NoteCategory.WOODY },
    { name: "Vetiver", slug: "vetiver", category: NoteCategory.WOODY },
    { name: "Oud", slug: "oud", category: NoteCategory.WOODY },
    { name: "Patchouli", slug: "patchouli", category: NoteCategory.WOODY },
    { name: "Guaiac Wood", slug: "guaiac-wood", category: NoteCategory.WOODY },
    { name: "Birch", slug: "birch", category: NoteCategory.WOODY },

    // Spicy
    { name: "Black Pepper", slug: "black-pepper", category: NoteCategory.SPICY },
    { name: "Cardamom", slug: "cardamom", category: NoteCategory.SPICY },
    { name: "Cinnamon", slug: "cinnamon", category: NoteCategory.SPICY },
    { name: "Clove", slug: "clove", category: NoteCategory.SPICY },
    { name: "Ginger", slug: "ginger", category: NoteCategory.SPICY },
    { name: "Nutmeg", slug: "nutmeg", category: NoteCategory.SPICY },
    { name: "Saffron", slug: "saffron", category: NoteCategory.SPICY },
    { name: "Pink Pepper", slug: "pink-pepper", category: NoteCategory.SPICY },

    // Fresh
    { name: "Sea Salt", slug: "sea-salt", category: NoteCategory.FRESH },
    { name: "Mint", slug: "mint", category: NoteCategory.FRESH },
    { name: "Cucumber", slug: "cucumber", category: NoteCategory.FRESH },
    { name: "Green Tea", slug: "green-tea", category: NoteCategory.FRESH },

    // Aquatic
    { name: "Marine Notes", slug: "marine-notes", category: NoteCategory.AQUATIC },
    { name: "Ambergris", slug: "ambergris", category: NoteCategory.AQUATIC },

    // Fruity
    { name: "Apple", slug: "apple", category: NoteCategory.FRUITY },
    { name: "Peach", slug: "peach", category: NoteCategory.FRUITY },
    { name: "Pineapple", slug: "pineapple", category: NoteCategory.FRUITY },
    { name: "Blackcurrant", slug: "blackcurrant", category: NoteCategory.FRUITY },
    { name: "Raspberry", slug: "raspberry", category: NoteCategory.FRUITY },
    { name: "Fig", slug: "fig", category: NoteCategory.FRUITY },
    { name: "Pear", slug: "pear", category: NoteCategory.FRUITY },

    // Gourmand
    { name: "Vanilla", slug: "vanilla", category: NoteCategory.GOURMAND },
    { name: "Tonka Bean", slug: "tonka-bean", category: NoteCategory.GOURMAND },
    { name: "Cocoa", slug: "cocoa", category: NoteCategory.GOURMAND },
    { name: "Coffee", slug: "coffee", category: NoteCategory.GOURMAND },
    { name: "Caramel", slug: "caramel", category: NoteCategory.GOURMAND },
    { name: "Honey", slug: "honey", category: NoteCategory.GOURMAND },
    { name: "Almond", slug: "almond", category: NoteCategory.GOURMAND },

    // Amber/Oriental
    { name: "Amber", slug: "amber", category: NoteCategory.AMBER },
    { name: "Benzoin", slug: "benzoin", category: NoteCategory.AMBER },
    { name: "Incense", slug: "incense", category: NoteCategory.ORIENTAL },
    { name: "Myrrh", slug: "myrrh", category: NoteCategory.ORIENTAL },
    { name: "Frankincense", slug: "frankincense", category: NoteCategory.ORIENTAL },

    // Musk
    { name: "White Musk", slug: "white-musk", category: NoteCategory.MUSK },
    { name: "Musk", slug: "musk", category: NoteCategory.MUSK },

    // Leather
    { name: "Leather", slug: "leather", category: NoteCategory.LEATHER },
    { name: "Suede", slug: "suede", category: NoteCategory.LEATHER },

    // Green
    { name: "Basil", slug: "basil", category: NoteCategory.GREEN },
    { name: "Galbanum", slug: "galbanum", category: NoteCategory.GREEN },
    { name: "Green Notes", slug: "green-notes", category: NoteCategory.GREEN },

    // Aromatic
    { name: "Sage", slug: "sage", category: NoteCategory.AROMATIC },
    { name: "Rosemary", slug: "rosemary", category: NoteCategory.AROMATIC },
    { name: "Geranium", slug: "geranium", category: NoteCategory.AROMATIC },
    { name: "Thyme", slug: "thyme", category: NoteCategory.AROMATIC },

    // Additional notes
    { name: "Tobacco", slug: "tobacco", category: NoteCategory.AROMATIC },
    { name: "Praline", slug: "praline", category: NoteCategory.GOURMAND },
    { name: "Rum", slug: "rum", category: NoteCategory.GOURMAND },
    { name: "Whiskey", slug: "whiskey", category: NoteCategory.GOURMAND },
    { name: "Coconut", slug: "coconut", category: NoteCategory.GOURMAND },
    { name: "Heliotrope", slug: "heliotrope", category: NoteCategory.FLORAL },
    { name: "Neroli", slug: "neroli", category: NoteCategory.FLORAL },
    { name: "Orchid", slug: "orchid", category: NoteCategory.FLORAL },
    { name: "Freesia", slug: "freesia", category: NoteCategory.FLORAL },
    { name: "Carnation", slug: "carnation", category: NoteCategory.FLORAL },
    { name: "Lily", slug: "lily", category: NoteCategory.FLORAL },
    { name: "Plum", slug: "plum", category: NoteCategory.FRUITY },
    { name: "Cherry", slug: "cherry", category: NoteCategory.FRUITY },
    { name: "Lychee", slug: "lychee", category: NoteCategory.FRUITY },
    { name: "Passion Fruit", slug: "passion-fruit", category: NoteCategory.FRUITY },
    { name: "Strawberry", slug: "strawberry", category: NoteCategory.FRUITY },
    { name: "Apricot", slug: "apricot", category: NoteCategory.FRUITY },
    { name: "Cassis", slug: "cassis", category: NoteCategory.FRUITY },
    { name: "Agarwood", slug: "agarwood", category: NoteCategory.WOODY },
    { name: "Cypress", slug: "cypress", category: NoteCategory.WOODY },
    { name: "Pine", slug: "pine", category: NoteCategory.WOODY },
    { name: "Oakmoss", slug: "oakmoss", category: NoteCategory.WOODY },
    { name: "Cashmeran", slug: "cashmeran", category: NoteCategory.WOODY },
    { name: "Elemi", slug: "elemi", category: NoteCategory.AROMATIC },
    { name: "Aldehydes", slug: "aldehydes", category: NoteCategory.FRESH },
    { name: "Ozonic Notes", slug: "ozonic-notes", category: NoteCategory.FRESH },
    { name: "Water Notes", slug: "water-notes", category: NoteCategory.AQUATIC },
    { name: "Seaweed", slug: "seaweed", category: NoteCategory.AQUATIC },
    { name: "Moss", slug: "moss", category: NoteCategory.GREEN },
    { name: "Ivy", slug: "ivy", category: NoteCategory.GREEN },
    { name: "Papyrus", slug: "papyrus", category: NoteCategory.WOODY },
    { name: "Bamboo", slug: "bamboo", category: NoteCategory.GREEN },
    { name: "Labdanum", slug: "labdanum", category: NoteCategory.AMBER },
    { name: "Opoponax", slug: "opoponax", category: NoteCategory.ORIENTAL },
    { name: "Civet", slug: "civet", category: NoteCategory.MUSK },
    { name: "Castoreum", slug: "castoreum", category: NoteCategory.LEATHER },
    { name: "Smoky Notes", slug: "smoky-notes", category: NoteCategory.AROMATIC },
    { name: "Artemisia", slug: "artemisia", category: NoteCategory.AROMATIC },
    { name: "Juniper", slug: "juniper", category: NoteCategory.AROMATIC },
    { name: "Anise", slug: "anise", category: NoteCategory.SPICY },
    { name: "Star Anise", slug: "star-anise", category: NoteCategory.SPICY },
    { name: "Cumin", slug: "cumin", category: NoteCategory.SPICY },
    { name: "Gardenia", slug: "gardenia", category: NoteCategory.FLORAL },
    { name: "Honeysuckle", slug: "honeysuckle", category: NoteCategory.FLORAL },
    { name: "Lotus", slug: "lotus", category: NoteCategory.FLORAL },
  ];

  const notes: Record<string, string> = {};
  for (const note of notesData) {
    const created = await prisma.note.create({ data: note });
    notes[note.slug] = created.id;
  }

  console.log(`Created ${Object.keys(notes).length} notes`);

  console.log("Creating brands...");

  // Create Brands
  const brandsData = [
    { name: "Dior", slug: "dior", country: "France" },
    { name: "Chanel", slug: "chanel", country: "France" },
    { name: "Tom Ford", slug: "tom-ford", country: "United States" },
    { name: "Creed", slug: "creed", country: "France" },
    { name: "Maison Francis Kurkdjian", slug: "maison-francis-kurkdjian", country: "France" },
    { name: "Yves Saint Laurent", slug: "yves-saint-laurent", country: "France" },
    { name: "Giorgio Armani", slug: "giorgio-armani", country: "Italy" },
    { name: "Versace", slug: "versace", country: "Italy" },
    { name: "Prada", slug: "prada", country: "Italy" },
    { name: "Le Labo", slug: "le-labo", country: "United States" },
    { name: "Byredo", slug: "byredo", country: "Sweden" },
    { name: "Parfums de Marly", slug: "parfums-de-marly", country: "France" },
    { name: "Jean Paul Gaultier", slug: "jean-paul-gaultier", country: "France" },
    { name: "Mugler", slug: "mugler", country: "France" },
    { name: "Jo Malone", slug: "jo-malone", country: "United Kingdom" },
    { name: "Paco Rabanne", slug: "paco-rabanne", country: "Spain" },
    { name: "Gucci", slug: "gucci", country: "Italy" },
    { name: "Dolce & Gabbana", slug: "dolce-gabbana", country: "Italy" },
    { name: "Hermès", slug: "hermes", country: "France" },
    { name: "Bvlgari", slug: "bvlgari", country: "Italy" },
    { name: "Calvin Klein", slug: "calvin-klein", country: "United States" },
    { name: "Hugo Boss", slug: "hugo-boss", country: "Germany" },
    { name: "Montblanc", slug: "montblanc", country: "Germany" },
    { name: "Carolina Herrera", slug: "carolina-herrera", country: "Venezuela" },
    { name: "Givenchy", slug: "givenchy", country: "France" },
    { name: "Burberry", slug: "burberry", country: "United Kingdom" },
    { name: "Valentino", slug: "valentino", country: "Italy" },
    { name: "Lancôme", slug: "lancome", country: "France" },
    { name: "Issey Miyake", slug: "issey-miyake", country: "Japan" },
    { name: "Nautica", slug: "nautica", country: "United States" },
    { name: "Azzaro", slug: "azzaro", country: "France" },
    { name: "Mont Blanc", slug: "mont-blanc", country: "Germany" },
    { name: "Initio", slug: "initio", country: "France" },
    { name: "Xerjoff", slug: "xerjoff", country: "Italy" },
    { name: "Amouage", slug: "amouage", country: "Oman" },
    { name: "Nishane", slug: "nishane", country: "Turkey" },
    { name: "Mancera", slug: "mancera", country: "France" },
    { name: "Montale", slug: "montale", country: "France" },
    { name: "Kilian", slug: "kilian", country: "France" },
    { name: "Bond No. 9", slug: "bond-no-9", country: "United States" },
    { name: "Diptyque", slug: "diptyque", country: "France" },
    { name: "Frederic Malle", slug: "frederic-malle", country: "France" },
  ];

  const brands: Record<string, string> = {};
  for (const brand of brandsData) {
    const created = await prisma.brand.create({ data: brand });
    brands[brand.slug] = created.id;
  }

  console.log(`Created ${Object.keys(brands).length} brands`);

  console.log("Creating fragrances...");

  // Create Fragrances with notes (trimmed for brevity - key ones)
  const fragrancesData = [
    {
      name: "Sauvage",
      slug: "sauvage",
      brandSlug: "dior",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 2015,
      description: "A radically fresh composition, raw and noble all at once.",
      image: "https://fimgs.net/mdimg/perfume/375x500.31861.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "black-pepper", layer: NoteLayer.TOP },
        { slug: "lavender", layer: NoteLayer.MIDDLE },
        { slug: "geranium", layer: NoteLayer.MIDDLE },
        { slug: "ambergris", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Bleu de Chanel",
      slug: "bleu-de-chanel",
      brandSlug: "chanel",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2014,
      description: "A woody, aromatic fragrance for the man who defies convention.",
      image: "https://fimgs.net/mdimg/perfume/375x500.25967.jpg",
      notes: [
        { slug: "grapefruit", layer: NoteLayer.TOP },
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "mint", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "ginger", layer: NoteLayer.MIDDLE },
        { slug: "incense", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Aventus",
      slug: "aventus",
      brandSlug: "creed",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2010,
      description: "A bold, masculine fragrance celebrating strength, success, and vision.",
      image: "https://fimgs.net/mdimg/perfume/375x500.9828.jpg",
      notes: [
        { slug: "pineapple", layer: NoteLayer.TOP },
        { slug: "blackcurrant", layer: NoteLayer.TOP },
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "apple", layer: NoteLayer.TOP },
        { slug: "birch", layer: NoteLayer.MIDDLE },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Baccarat Rouge 540",
      slug: "baccarat-rouge-540",
      brandSlug: "maison-francis-kurkdjian",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2015,
      description: "A poetic alchemy, a series of harmonies and dissonances.",
      image: "https://fimgs.net/mdimg/perfume/375x500.33519.jpg",
      notes: [
        { slug: "saffron", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "ambergris", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Oud Wood",
      slug: "oud-wood",
      brandSlug: "tom-ford",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2007,
      description: "One of the most rare, precious and expensive ingredients in a perfumer's arsenal.",
      image: "https://fimgs.net/mdimg/perfume/375x500.1827.jpg",
      notes: [
        { slug: "cardamom", layer: NoteLayer.TOP },
        { slug: "oud", layer: NoteLayer.MIDDLE },
        { slug: "sandalwood", layer: NoteLayer.MIDDLE },
        { slug: "vetiver", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Tobacco Vanille",
      slug: "tobacco-vanille",
      brandSlug: "tom-ford",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2007,
      description: "Opulent. Warm. Iconic. Tom Ford's contemporary take on old-world gentlemen's club.",
      image: "https://fimgs.net/mdimg/perfume/375x500.1826.jpg",
      notes: [
        { slug: "ginger", layer: NoteLayer.TOP },
        { slug: "cinnamon", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "cocoa", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Santal 33",
      slug: "santal-33",
      brandSlug: "le-labo",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2011,
      description: "A sandalwood-based fragrance with leathery and smoky notes.",
      image: "https://fimgs.net/mdimg/perfume/375x500.12210.jpg",
      notes: [
        { slug: "cardamom", layer: NoteLayer.TOP },
        { slug: "iris", layer: NoteLayer.MIDDLE },
        { slug: "violet", layer: NoteLayer.MIDDLE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "leather", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Acqua di Gio",
      slug: "acqua-di-gio",
      brandSlug: "giorgio-armani",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 1996,
      description: "A fresh aquatic fragrance inspired by the beauty of Pantelleria.",
      image: "https://fimgs.net/mdimg/perfume/375x500.299.jpg",
      notes: [
        { slug: "lime", layer: NoteLayer.TOP },
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "marine-notes", layer: NoteLayer.MIDDLE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "patchouli", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Eros",
      slug: "eros",
      brandSlug: "versace",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 2012,
      description: "A powerful fragrance named after the Greek god of love.",
      image: "https://fimgs.net/mdimg/perfume/375x500.16829.jpg",
      notes: [
        { slug: "mint", layer: NoteLayer.TOP },
        { slug: "green-notes", layer: NoteLayer.TOP },
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "tonka-bean", layer: NoteLayer.MIDDLE },
        { slug: "ambergris", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "vetiver", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Black Opium",
      slug: "black-opium",
      brandSlug: "yves-saint-laurent",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2014,
      description: "A seductively intoxicating fragrance with coffee and vanilla.",
      image: "https://fimgs.net/mdimg/perfume/375x500.25324.jpg",
      notes: [
        { slug: "pink-pepper", layer: NoteLayer.TOP },
        { slug: "pear", layer: NoteLayer.TOP },
        { slug: "coffee", layer: NoteLayer.MIDDLE },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "patchouli", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Coco Mademoiselle",
      slug: "coco-mademoiselle",
      brandSlug: "chanel",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2001,
      description: "A fresh, oriental fragrance for the confident, passionate woman.",
      image: "https://fimgs.net/mdimg/perfume/375x500.611.jpg",
      notes: [
        { slug: "orange", layer: NoteLayer.TOP },
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "patchouli", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Layton",
      slug: "layton",
      brandSlug: "parfums-de-marly",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2016,
      description: "A refined, masculine fragrance with apple and vanilla.",
      image: "https://fimgs.net/mdimg/perfume/375x500.40458.jpg",
      notes: [
        { slug: "apple", layer: NoteLayer.TOP },
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "lavender", layer: NoteLayer.MIDDLE },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "cardamom", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    // Additional fragrances
    {
      name: "La Nuit de L'Homme",
      slug: "la-nuit-de-lhomme",
      brandSlug: "yves-saint-laurent",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 2009,
      description: "A bold, elegant, and mysterious fragrance for the modern seducer.",
      image: "https://fimgs.net/mdimg/perfume/375x500.5523.jpg",
      notes: [
        { slug: "cardamom", layer: NoteLayer.TOP },
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "lavender", layer: NoteLayer.MIDDLE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "vetiver", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "1 Million",
      slug: "1-million",
      brandSlug: "paco-rabanne",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 2008,
      description: "A leather and spicy fragrance that exudes confidence and luxury.",
      image: "https://fimgs.net/mdimg/perfume/375x500.3747.jpg",
      notes: [
        { slug: "grapefruit", layer: NoteLayer.TOP },
        { slug: "mint", layer: NoteLayer.TOP },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "cinnamon", layer: NoteLayer.MIDDLE },
        { slug: "leather", layer: NoteLayer.BASE },
        { slug: "amber", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Invictus",
      slug: "invictus",
      brandSlug: "paco-rabanne",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 2013,
      description: "A fresh, powerful fragrance for the champion in every man.",
      image: "https://fimgs.net/mdimg/perfume/375x500.20657.jpg",
      notes: [
        { slug: "grapefruit", layer: NoteLayer.TOP },
        { slug: "marine-notes", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "ambergris", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Le Male",
      slug: "le-male",
      brandSlug: "jean-paul-gaultier",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 1995,
      description: "A fresh oriental fragrance that balances strength with sensuality.",
      image: "https://fimgs.net/mdimg/perfume/375x500.430.jpg",
      notes: [
        { slug: "mint", layer: NoteLayer.TOP },
        { slug: "lavender", layer: NoteLayer.TOP },
        { slug: "cardamom", layer: NoteLayer.TOP },
        { slug: "orange-blossom", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Angel",
      slug: "angel",
      brandSlug: "mugler",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 1992,
      description: "A revolutionary gourmand fragrance with a heavenly star-shaped bottle.",
      image: "https://fimgs.net/mdimg/perfume/375x500.705.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "honey", layer: NoteLayer.MIDDLE },
        { slug: "caramel", layer: NoteLayer.MIDDLE },
        { slug: "patchouli", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "cocoa", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Alien",
      slug: "alien",
      brandSlug: "mugler",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2005,
      description: "A radiant, woody-amber fragrance for women who dare to be different.",
      image: "https://fimgs.net/mdimg/perfume/375x500.2219.jpg",
      notes: [
        { slug: "jasmine", layer: NoteLayer.TOP },
        { slug: "cashmeran", layer: NoteLayer.MIDDLE },
        { slug: "amber", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Light Blue",
      slug: "light-blue",
      brandSlug: "dolce-gabbana",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.FEMININE,
      releaseYear: 2001,
      description: "A fresh, floral-fruity scent evoking the sensuality of Mediterranean life.",
      image: "https://fimgs.net/mdimg/perfume/375x500.485.jpg",
      notes: [
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "apple", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "The One",
      slug: "the-one",
      brandSlug: "dolce-gabbana",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2008,
      description: "A warm, spicy fragrance for the modern gentleman.",
      image: "https://fimgs.net/mdimg/perfume/375x500.3032.jpg",
      notes: [
        { slug: "grapefruit", layer: NoteLayer.TOP },
        { slug: "cinnamon", layer: NoteLayer.TOP },
        { slug: "ginger", layer: NoteLayer.MIDDLE },
        { slug: "cardamom", layer: NoteLayer.MIDDLE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "amber", layer: NoteLayer.BASE },
        { slug: "tobacco", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "La Vie Est Belle",
      slug: "la-vie-est-belle",
      brandSlug: "lancome",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2012,
      description: "A sweet iris gourmand fragrance celebrating the beauty of life.",
      image: "https://fimgs.net/mdimg/perfume/375x500.16953.jpg",
      notes: [
        { slug: "blackcurrant", layer: NoteLayer.TOP },
        { slug: "pear", layer: NoteLayer.TOP },
        { slug: "iris", layer: NoteLayer.MIDDLE },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "praline", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "patchouli", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Acqua di Gio Profumo",
      slug: "acqua-di-gio-profumo",
      brandSlug: "giorgio-armani",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2015,
      description: "A deeper, more intense evolution of the iconic aquatic fragrance.",
      image: "https://fimgs.net/mdimg/perfume/375x500.29727.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "marine-notes", layer: NoteLayer.TOP },
        { slug: "geranium", layer: NoteLayer.MIDDLE },
        { slug: "sage", layer: NoteLayer.MIDDLE },
        { slug: "incense", layer: NoteLayer.BASE },
        { slug: "amber", layer: NoteLayer.BASE },
        { slug: "patchouli", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Stronger With You",
      slug: "stronger-with-you",
      brandSlug: "giorgio-armani",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 2017,
      description: "A warm, spicy fragrance celebrating the power of connection.",
      image: "https://fimgs.net/mdimg/perfume/375x500.44058.jpg",
      notes: [
        { slug: "cardamom", layer: NoteLayer.TOP },
        { slug: "pink-pepper", layer: NoteLayer.TOP },
        { slug: "sage", layer: NoteLayer.MIDDLE },
        { slug: "cinnamon", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Good Girl",
      slug: "good-girl",
      brandSlug: "carolina-herrera",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2016,
      description: "A sensual, sophisticated fragrance in an iconic stiletto bottle.",
      image: "https://fimgs.net/mdimg/perfume/375x500.39254.jpg",
      notes: [
        { slug: "almond", layer: NoteLayer.TOP },
        { slug: "coffee", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "tuberose", layer: NoteLayer.MIDDLE },
        { slug: "cocoa", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "212 VIP",
      slug: "212-vip",
      brandSlug: "carolina-herrera",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2010,
      description: "A glamorous, addictive scent for the woman who lives life to the fullest.",
      image: "https://fimgs.net/mdimg/perfume/375x500.9893.jpg",
      notes: [
        { slug: "passion-fruit", layer: NoteLayer.TOP },
        { slug: "rum", layer: NoteLayer.TOP },
        { slug: "gardenia", layer: NoteLayer.MIDDLE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Miss Dior",
      slug: "miss-dior",
      brandSlug: "dior",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2017,
      description: "A fresh, romantic fragrance with a couture spirit.",
      image: "https://fimgs.net/mdimg/perfume/375x500.44656.jpg",
      notes: [
        { slug: "mandarin", layer: NoteLayer.TOP },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "peony", layer: NoteLayer.MIDDLE },
        { slug: "iris", layer: NoteLayer.MIDDLE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "patchouli", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "J'adore",
      slug: "jadore",
      brandSlug: "dior",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 1999,
      description: "An iconic floral bouquet that embodies absolute femininity.",
      image: "https://fimgs.net/mdimg/perfume/375x500.212.jpg",
      notes: [
        { slug: "pear", layer: NoteLayer.TOP },
        { slug: "mandarin", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "ylang-ylang", layer: NoteLayer.MIDDLE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Dior Homme Intense",
      slug: "dior-homme-intense",
      brandSlug: "dior",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2011,
      description: "A sophisticated iris fragrance with sensual depth.",
      image: "https://fimgs.net/mdimg/perfume/375x500.12580.jpg",
      notes: [
        { slug: "lavender", layer: NoteLayer.TOP },
        { slug: "iris", layer: NoteLayer.MIDDLE },
        { slug: "amber", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "vetiver", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Terre d'Hermès",
      slug: "terre-dhermes",
      brandSlug: "hermes",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 2006,
      description: "An earthy, mineral fragrance celebrating the connection between man and earth.",
      image: "https://fimgs.net/mdimg/perfume/375x500.1961.jpg",
      notes: [
        { slug: "orange", layer: NoteLayer.TOP },
        { slug: "grapefruit", layer: NoteLayer.TOP },
        { slug: "black-pepper", layer: NoteLayer.MIDDLE },
        { slug: "geranium", layer: NoteLayer.MIDDLE },
        { slug: "vetiver", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "benzoin", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Guilty",
      slug: "guilty",
      brandSlug: "gucci",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2019,
      description: "A bold, contemporary fragrance for the free-spirited woman.",
      image: "https://fimgs.net/mdimg/perfume/375x500.54916.jpg",
      notes: [
        { slug: "mandarin", layer: NoteLayer.TOP },
        { slug: "pink-pepper", layer: NoteLayer.TOP },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "violet", layer: NoteLayer.MIDDLE },
        { slug: "patchouli", layer: NoteLayer.BASE },
        { slug: "amber", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Bloom",
      slug: "bloom",
      brandSlug: "gucci",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2017,
      description: "A rich white floral scent that celebrates authenticity and diversity.",
      image: "https://fimgs.net/mdimg/perfume/375x500.45155.jpg",
      notes: [
        { slug: "jasmine", layer: NoteLayer.TOP },
        { slug: "tuberose", layer: NoteLayer.MIDDLE },
        { slug: "honeysuckle", layer: NoteLayer.MIDDLE },
      ],
    },
    {
      name: "L'Homme",
      slug: "lhomme-ysl",
      brandSlug: "yves-saint-laurent",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.MASCULINE,
      releaseYear: 2006,
      description: "An elegant, fresh woody fragrance for the sophisticated man.",
      image: "https://fimgs.net/mdimg/perfume/375x500.2666.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "ginger", layer: NoteLayer.TOP },
        { slug: "violet", layer: NoteLayer.MIDDLE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "vetiver", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Libre",
      slug: "libre",
      brandSlug: "yves-saint-laurent",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2019,
      description: "A fougère fragrance redefined for the fearless, free woman.",
      image: "https://fimgs.net/mdimg/perfume/375x500.55093.jpg",
      notes: [
        { slug: "mandarin", layer: NoteLayer.TOP },
        { slug: "lavender", layer: NoteLayer.TOP },
        { slug: "orange-blossom", layer: NoteLayer.MIDDLE },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Chanel No. 5",
      slug: "chanel-no-5",
      brandSlug: "chanel",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 1921,
      description: "The world's most iconic fragrance, a timeless symbol of femininity.",
      image: "https://fimgs.net/mdimg/perfume/375x500.608.jpg",
      notes: [
        { slug: "aldehydes", layer: NoteLayer.TOP },
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "ylang-ylang", layer: NoteLayer.MIDDLE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Chance Eau Tendre",
      slug: "chance-eau-tendre",
      brandSlug: "chanel",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.FEMININE,
      releaseYear: 2010,
      description: "A delicate, fruity-floral fragrance full of tenderness.",
      image: "https://fimgs.net/mdimg/perfume/375x500.9055.jpg",
      notes: [
        { slug: "grapefruit", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Noir Extreme",
      slug: "noir-extreme",
      brandSlug: "tom-ford",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2015,
      description: "An intensely warm and spicy oriental fragrance.",
      image: "https://fimgs.net/mdimg/perfume/375x500.29664.jpg",
      notes: [
        { slug: "cardamom", layer: NoteLayer.TOP },
        { slug: "mandarin", layer: NoteLayer.TOP },
        { slug: "nutmeg", layer: NoteLayer.MIDDLE },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "amber", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Lost Cherry",
      slug: "lost-cherry",
      brandSlug: "tom-ford",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2018,
      description: "A tempting, provocative fragrance built around black cherry.",
      image: "https://fimgs.net/mdimg/perfume/375x500.52434.jpg",
      notes: [
        { slug: "cherry", layer: NoteLayer.TOP },
        { slug: "almond", layer: NoteLayer.TOP },
        { slug: "plum", layer: NoteLayer.MIDDLE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "vanilla", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Rose Prick",
      slug: "rose-prick",
      brandSlug: "tom-ford",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2020,
      description: "A bold rose fragrance with a thorny edge.",
      image: "https://fimgs.net/mdimg/perfume/375x500.60116.jpg",
      notes: [
        { slug: "rose", layer: NoteLayer.TOP },
        { slug: "saffron", layer: NoteLayer.TOP },
        { slug: "tuberose", layer: NoteLayer.MIDDLE },
        { slug: "patchouli", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Silver Mountain Water",
      slug: "silver-mountain-water",
      brandSlug: "creed",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 1995,
      description: "A fresh, invigorating scent inspired by the Swiss Alps.",
      image: "https://fimgs.net/mdimg/perfume/375x500.467.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "mandarin", layer: NoteLayer.TOP },
        { slug: "green-tea", layer: NoteLayer.MIDDLE },
        { slug: "black-pepper", layer: NoteLayer.MIDDLE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Green Irish Tweed",
      slug: "green-irish-tweed",
      brandSlug: "creed",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 1985,
      description: "A timeless green fragrance evoking the Irish countryside.",
      image: "https://fimgs.net/mdimg/perfume/375x500.474.jpg",
      notes: [
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "iris", layer: NoteLayer.MIDDLE },
        { slug: "violet", layer: NoteLayer.MIDDLE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "ambergris", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Viking",
      slug: "viking",
      brandSlug: "creed",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2017,
      description: "A bold, invigorating fragrance celebrating Norse explorers.",
      image: "https://fimgs.net/mdimg/perfume/375x500.44261.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "pink-pepper", layer: NoteLayer.TOP },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "geranium", layer: NoteLayer.MIDDLE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "vetiver", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Another 13",
      slug: "another-13",
      brandSlug: "le-labo",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2010,
      description: "A unique, sensual fragrance that becomes one with your skin.",
      image: "https://fimgs.net/mdimg/perfume/375x500.10918.jpg",
      notes: [
        { slug: "jasmine", layer: NoteLayer.TOP },
        { slug: "musk", layer: NoteLayer.MIDDLE },
        { slug: "ambergris", layer: NoteLayer.BASE },
        { slug: "moss", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Rose 31",
      slug: "rose-31",
      brandSlug: "le-labo",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2006,
      description: "A warm, spicy rose for those who dare to be different.",
      image: "https://fimgs.net/mdimg/perfume/375x500.4218.jpg",
      notes: [
        { slug: "rose", layer: NoteLayer.TOP },
        { slug: "cumin", layer: NoteLayer.MIDDLE },
        { slug: "cedar", layer: NoteLayer.MIDDLE },
        { slug: "amber", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Gypsy Water",
      slug: "gypsy-water",
      brandSlug: "byredo",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2008,
      description: "A romantic fragrance inspired by the free-spirited Romani lifestyle.",
      image: "https://fimgs.net/mdimg/perfume/375x500.5247.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "juniper", layer: NoteLayer.TOP },
        { slug: "incense", layer: NoteLayer.MIDDLE },
        { slug: "pine", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Bal d'Afrique",
      slug: "bal-dafrique",
      brandSlug: "byredo",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2009,
      description: "A vibrant, joyful fragrance celebrating African culture and Parisian nightlife.",
      image: "https://fimgs.net/mdimg/perfume/375x500.7788.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "lemon", layer: NoteLayer.TOP },
        { slug: "neroli", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "violet", layer: NoteLayer.MIDDLE },
        { slug: "vetiver", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "amber", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "BR540 Extrait",
      slug: "baccarat-rouge-540-extrait",
      brandSlug: "maison-francis-kurkdjian",
      concentration: Concentration.EXTRAIT,
      gender: Gender.UNISEX,
      releaseYear: 2017,
      description: "An intensified, longer-lasting version of the iconic Baccarat Rouge 540.",
      image: "https://fimgs.net/mdimg/perfume/375x500.45189.jpg",
      notes: [
        { slug: "saffron", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "ambergris", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Grand Soir",
      slug: "grand-soir",
      brandSlug: "maison-francis-kurkdjian",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2016,
      description: "A warm, sensual amber fragrance for elegant evenings.",
      image: "https://fimgs.net/mdimg/perfume/375x500.41105.jpg",
      notes: [
        { slug: "amber", layer: NoteLayer.TOP },
        { slug: "labdanum", layer: NoteLayer.MIDDLE },
        { slug: "benzoin", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Herod",
      slug: "herod",
      brandSlug: "parfums-de-marly",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2012,
      description: "A rich, tobacco-laden fragrance fit for royalty.",
      image: "https://fimgs.net/mdimg/perfume/375x500.17082.jpg",
      notes: [
        { slug: "cinnamon", layer: NoteLayer.TOP },
        { slug: "tobacco", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Pegasus",
      slug: "pegasus",
      brandSlug: "parfums-de-marly",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2011,
      description: "A fresh, almond-vanilla fragrance with mythical allure.",
      image: "https://fimgs.net/mdimg/perfume/375x500.13198.jpg",
      notes: [
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "almond", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "amber", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Delina",
      slug: "delina",
      brandSlug: "parfums-de-marly",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2017,
      description: "A romantic, rosy fragrance with modern sophistication.",
      image: "https://fimgs.net/mdimg/perfume/375x500.43027.jpg",
      notes: [
        { slug: "lychee", layer: NoteLayer.TOP },
        { slug: "bergamot", layer: NoteLayer.TOP },
        { slug: "rose", layer: NoteLayer.MIDDLE },
        { slug: "peony", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Side Effect",
      slug: "side-effect",
      brandSlug: "initio",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2016,
      description: "An addictive, gourmand fragrance with rum and tobacco.",
      image: "https://fimgs.net/mdimg/perfume/375x500.40926.jpg",
      notes: [
        { slug: "rum", layer: NoteLayer.TOP },
        { slug: "cinnamon", layer: NoteLayer.TOP },
        { slug: "tobacco", layer: NoteLayer.MIDDLE },
        { slug: "vanilla", layer: NoteLayer.BASE },
        { slug: "benzoin", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Oud for Greatness",
      slug: "oud-for-greatness",
      brandSlug: "initio",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.UNISEX,
      releaseYear: 2018,
      description: "A powerful oud fragrance for those destined for greatness.",
      image: "https://fimgs.net/mdimg/perfume/375x500.51115.jpg",
      notes: [
        { slug: "saffron", layer: NoteLayer.TOP },
        { slug: "nutmeg", layer: NoteLayer.TOP },
        { slug: "oud", layer: NoteLayer.MIDDLE },
        { slug: "lavender", layer: NoteLayer.MIDDLE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Portrait of a Lady",
      slug: "portrait-of-a-lady",
      brandSlug: "frederic-malle",
      concentration: Concentration.EAU_DE_PARFUM,
      gender: Gender.FEMININE,
      releaseYear: 2010,
      description: "A sumptuous rose and patchouli masterpiece by Dominique Ropion.",
      image: "https://fimgs.net/mdimg/perfume/375x500.11003.jpg",
      notes: [
        { slug: "rose", layer: NoteLayer.TOP },
        { slug: "clove", layer: NoteLayer.TOP },
        { slug: "raspberry", layer: NoteLayer.MIDDLE },
        { slug: "incense", layer: NoteLayer.MIDDLE },
        { slug: "patchouli", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "musk", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "L'Eau d'Issey",
      slug: "leau-dissey",
      brandSlug: "issey-miyake",
      concentration: Concentration.EAU_DE_TOILETTE,
      gender: Gender.FEMININE,
      releaseYear: 1992,
      description: "A revolutionary aquatic floral that captures the essence of water.",
      image: "https://fimgs.net/mdimg/perfume/375x500.353.jpg",
      notes: [
        { slug: "rose", layer: NoteLayer.TOP },
        { slug: "lotus", layer: NoteLayer.TOP },
        { slug: "lily", layer: NoteLayer.MIDDLE },
        { slug: "peony", layer: NoteLayer.MIDDLE },
        { slug: "musk", layer: NoteLayer.BASE },
        { slug: "cedar", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Bleu de Chanel Parfum",
      slug: "bleu-de-chanel-parfum",
      brandSlug: "chanel",
      concentration: Concentration.PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2018,
      description: "The most intense and refined expression of Bleu de Chanel.",
      image: "https://fimgs.net/mdimg/perfume/375x500.52029.jpg",
      notes: [
        { slug: "grapefruit", layer: NoteLayer.TOP },
        { slug: "mint", layer: NoteLayer.TOP },
        { slug: "jasmine", layer: NoteLayer.MIDDLE },
        { slug: "cedar", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
        { slug: "tonka-bean", layer: NoteLayer.BASE },
      ],
    },
    {
      name: "Sauvage Elixir",
      slug: "sauvage-elixir",
      brandSlug: "dior",
      concentration: Concentration.PARFUM,
      gender: Gender.MASCULINE,
      releaseYear: 2021,
      description: "The most concentrated and potent version of Sauvage.",
      image: "https://fimgs.net/mdimg/perfume/375x500.67943.jpg",
      notes: [
        { slug: "grapefruit", layer: NoteLayer.TOP },
        { slug: "cinnamon", layer: NoteLayer.TOP },
        { slug: "nutmeg", layer: NoteLayer.TOP },
        { slug: "lavender", layer: NoteLayer.MIDDLE },
        { slug: "vetiver", layer: NoteLayer.BASE },
        { slug: "amber", layer: NoteLayer.BASE },
        { slug: "sandalwood", layer: NoteLayer.BASE },
      ],
    },
  ];

  for (const fragranceData of fragrancesData) {
    const fragrance = await prisma.fragrance.create({
      data: {
        name: fragranceData.name,
        slug: fragranceData.slug,
        brandId: brands[fragranceData.brandSlug],
        concentration: fragranceData.concentration,
        gender: fragranceData.gender,
        releaseYear: fragranceData.releaseYear,
        description: fragranceData.description,
        image: fragranceData.image,
      },
    });

    // Create fragrance notes
    for (const noteData of fragranceData.notes) {
      if (notes[noteData.slug]) {
        await prisma.fragranceNote.create({
          data: {
            fragranceId: fragrance.id,
            noteId: notes[noteData.slug],
            layer: noteData.layer,
          },
        });
      }
    }
  }

  const fragranceCount = await prisma.fragrance.count();
  console.log(`Created ${fragranceCount} fragrances`);

  console.log("Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
